---
new_page_extension: md
auto_deploy: false
admin_path: static/wp-admin
webhook_url: 
sections:
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/*"
- type: directory
  path: content/categories
  label: Categories
  create: documents
  match: "**/*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  new_doc_ext: mdx
  templates:
  - post
upload_dir: content/posts/img
public_path: "./img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn develop
